# use google api to find place id
ALL_SHOPS = [
    # {
    #     "id": 0,
    #     "name": "Bergin HQ",
    #     "address": {
    #         "id": 0,
    #         "address_1": "3404 Sugar Pine Dr",
    #         "address_2": "",
    #         "address_3": "",
    #         "city": "McKinney",
    #         "state": "Texas",
    #         "postal_code": 75070,
    #         "latitude": 33.168869,
    #         "longitude": -96.696509,
    #     },
    #     "is_verified": True,
    #     "place_id": "ChIJ2wLIJKoWTIYRSdmEA4kX3Zk",
    # },
    # {
    #     "id": 1,
    #     "name": "Garcia HQ",
    #     "address": {
    #         "id": 1,
    #         "address_1": "6020 Hidden Pine Ln",
    #         "address_2": "",
    #         "address_3": "",
    #         "city": "McKinney",
    #         "state": "Texas",
    #         "postal_code": 75070,
    #         "latitude": 33.173578,
    #         "longitude": -96.694958,
    #     },
    #     "is_verified": True,
    #     "place_id": "ChIJ2wLIJKoWTIYRSdmEA4kX3Zk",
    # },
    {
        "id": 2,
        "name": "Domar Automotive Inc",
        "address": {
            "id": 2,
            "address_1": "4006 W Plano Pkwy Suite 135",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75093,
            "latitude": 33.009562,
            "longitude": -96.768249,
        },
        "is_verified": True,
        "place_id": "ChIJI6_hnX0nTIYRJrGqq7r7GSY",
    },
    {
        "id": 3,
        "name": "Spring Creek Auto Repair",
        "address": {
            "id": 3,
            "address_1": "5401 Alma Dr",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75023,
            "latitude": 33.055777,
            "longitude": -96.710514,
        },
        "is_verified": True,
        "place_id": "ChIJqbfpdEoYTIYRJkO3qfkG1ko",
    },
    {
        "id": 4,
        "name": "Community Auto Repair",
        "address": {
            "id": 4,
            "address_1": "901 W Spring Creek Pkwy # 100",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75023,
            "latitude": 33.057085,
            "longitude": -96.710584,
        },
        "is_verified": True,
        "place_id": "ChIJm2dKkzUYTIYRpWocoqfgSL4",
    },
    {
        "id": 5,
        "name": "The Auto Shop",
        "address": {
            "id": 5,
            "address_1": "2560 E Plano Pkwy",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75074,
            "latitude": 33.006419,
            "longitude": -96.680518,
        },
        "is_verified": True,
        "place_id": "ChIJqWtprUYZTIYRjgqpKwfufxA",
    },
    {
        "id": 6,
        "name": "Major Automotive",
        "address": {
            "id": 6,
            "address_1": "3104 S Rigsbee Dr",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75074,
            "latitude": 33.013875,
            "longitude": -96.672315,
        },
        "is_verified": True,
        "place_id": "ChIJCT_clmcZTIYRICAwteigWUU",
    },
    {
        "id": 7,
        "name": "Marlow Automotive",
        "address": {
            "id": 7,
            "address_1": "1713 N Central Expy",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75075,
            "latitude": 33.02293,
            "longitude": -96.710872,
        },
        "is_verified": True,
        "place_id": "ChIJv7HotvwYTIYRC_E23Rw15BU",
    },
    {
        "id": 8,
        "name": "Integrity 1st Automotive",
        "address": {
            "id": 8,
            "address_1": "3330 Independence Pkwy #300",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75023,
            "latitude": 33.042019,
            "longitude": -96.752732,
        },
        "is_verified": True,
        "place_id": "ChIJX93VMYMiTIYRkJXPhh8dfD0",
    },
    {
        "id": 9,
        "name": "Plano Lube Auto Repair",
        "address": {
            "id": 9,
            "address_1": "711 W Parker Rd",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75023,
            "latitude": 33.041255,
            "longitude": -96.709658,
        },
        "is_verified": True,
        "place_id": "ChIJa34SiPwZTIYRJGqqGuXEOs8",
    },
    {
        "id": 10,
        "name": "Fix N Go",
        "address": {
            "id": 10,
            "address_1": "1920 Central Expy",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75074,
            "latitude": 33.027722,
            "longitude": -96.708449,
        },
        "is_verified": True,
        "place_id": "ChIJqym20f0YTIYRhFEF1ITV2Lw",
    },
    {
        "id": 11,
        "name": "Sav-Mor Automotive",
        "address": {
            "id": 11,
            "address_1": "1114 14th St",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75074,
            "latitude": 33.018054,
            "longitude": -96.698083,
        },
        "is_verified": True,
        "place_id": "ChIJxw0rMBoZTIYRIHcYYjDYMxQ",
    },
    {
        "id": 12,
        "name": "Plano Automotive",
        "address": {
            "id": 12,
            "address_1": "1800 K Ave",
            "address_2": "",
            "address_3": "",
            "city": "Plano",
            "state": "Texas",
            "postal_code": 75074,
            "latitude": 33.024209,
            "longitude": -96.69874,
        },
        "is_verified": True,
        "place_id": "ChIJIwekabAZTIYRGqluOYE-X-Y",
    },
]

